### ISSUE TITLE
Update Build-a-Duck Markdown to match current date and version

### ISSUE THREAD

**Issue by krook** [Code-and-Response/ClusterDuck-Protocol#101]
**Describe the bug**
The Markdown references March and a back-level version:

- Current: March 2020, v1.0.2
- Should be: July 2020, v1.1.6 (this is on the bottom of README.md)

**Comment by TimoWielink** [comment]
With the new Wiki, we are going to get rid of how to build a Duck PDF. We think that the wiki is easier to navigate in and it will be better up to date then a .md file.

**Comment by krook** [comment]
Sounds good.
