### ISSUE TITLE
Add support for WS2812 LED 

### ISSUE THREAD

**Issue by TimoWielink** [Code-and-Response/ClusterDuck-Protocol#111]
I would like to give feedback from the Ducks Health by changing the color of a LED.

For example, When the battery is almost dead (get info from AXP202x Chip on the Te beam) we turn the LED red and when its fully charged Green.

- [ ] Make example code for simple LED

- [ ] add support for FastLED Library.
To run different WS2812 LED chips we need to add FastLED library support.

- [ ] Intergrate with AXP202X Lbrary for changing colors

**Comment by TimoWielink** [comment]
What i noticed in my testing is that the 5V pin on the TTGO always provides power to the LED even when the board is off, we need to find a solution to power down the led (Maybe Mosfet?)

**Comment by TimoWielink** [comment]
Simple implementation of powering and setting up an LED #112

**Comment by nfeuer** [comment]
Merge PR #112 and #113. The support works for Heltec, but has issues with TTGO atm

**Comment by nfeuer** [comment]
#112 and #113 have been merged
