### ISSUE TITLE
document the IBM Watson cloud pieces

### ISSUE THREAD

**Issue by mkinney** [Code-and-Response/ClusterDuck-Protocol#12]
**Is your feature request related to a problem? Please describe.**
Add info on how to get started using the cloud.ibm.com stuff

**Describe the solution you'd like**
Create a step-by-step doc for going from nothing to seeing stuff happen in 

**Describe alternatives you've considered**
May consider using other cloud-stuffs. But, since this project was sponsored and uses IBM and IBM's cloud is free for lowest tier, I think it would be best to document how to get started with it.

**Additional context**
create new account, add device in ibm cloud, show how to get org/token, how to get messages flowing, etc.

**Comment by mkinney** [comment]
It is something like this:

1. Create an IBM account by visiting: https://internetofthings.ibmcloud.com/  (someone should verify this url)
2. Verify email
3. Forgot password
4. Create new bluemix free. (don't recall actual step here)
5. Add device (use mac address without colons?), type must be "PAPA" (or whatever you use in PapaExample), copy/paste token into PapaExample

**Comment by derekteay** [comment]
This has been completed, please see the [new README section](https://github.com/Code-and-Response/ClusterDuck-Protocol/blob/master/README.md#setting-up-the-ibm-watson-iot-platform)

**Comment by nfeuer** [comment]
Thanks @derekteay!
