### ISSUE TITLE
howToBuildADuck.md document has an error in the manual install section

### ISSUE THREAD

**Issue by dmandala** [Code-and-Response/ClusterDuck-Protocol#122]
The file at: https://github.com/Project-Owl/ClusterDuck-Protocol/blob/master/doc/howToBuildADuck.md#install-the-necessary-libraries-that-work-with-clusterduck-protocol has a bug in it.  

In the "Install ClusterDuck Protocol" section subheading "Manual Install" "Step 1. Clone the ClusterDuck Protocol onto your local machine `git clone https://github.com/Code-and-Response/ClusterDuck-Protocol.git`" is correct.  

The next step "Step 2." will not work as is, you need to be in the newly created "ClusterDuck-Protocol" directory for the next command to work.

Step 2 should be: 
"Step 2. change directory into the new "ClusterDuck-Protocol" directory you just created. `cd ClusterDuck-Protocol`"

The old "Step 2." should become "Step 3." and the rest of the manual install numbers should be incremented so there are now 9 steps not 8.

"Step 3. Pull all the Library submodules needed for the Arduino IDE `git submodule update --init --recursive`"

If you do not change into the new directory the  git command will fail and not pull all of the library submodules into place.

**Comment by TimoWielink** [comment]
Good find, It is very dependent on how you do this. If you first create a Folder called ClusterDuck-Protocol and then do the git clone you end up with two folders, and then you run into that error. If you do a git clone on for example your desktop or documents folder you only need to CD into your CDP folder. 

I will rewrite so its more clear. We are getting rid off the .md installation and switching to Wiki
