### ISSUE TITLE
Improve the Arduino library import process

### ISSUE THREAD

**Issue by mkinney** [Code-and-Response/ClusterDuck-Protocol#14]
**Is your feature request related to a problem? Please describe.**
There are libraries in a zip file in the repo. This is not a "best practice", but completely understand why/how it is the way it is.

**Describe the solution you'd like**
Create project files/some way to refer to other projects.

**Describe alternatives you've considered**
Ensure there are minimal binary/zip files in repo. Document steps to create a simple Mama/Papa from nothing (in regards to the library files)

**Additional context**
Looks like you can create dependencies (see https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ )

**Comment by krook** [comment]
Related to #9

**Comment by Salzi** [comment]
@TimoWielink Did #29 and #32 solves this?

**Comment by TimoWielink** [comment]
@Salzi yes!

**Comment by krook** [comment]
Both PRs have landed. Closing.
