### ISSUE TITLE
Document the solar panel/upgraded case changes

### ISSUE THREAD

**Issue by mkinney** [Code-and-Response/ClusterDuck-Protocol#16]
**Is your feature request related to a problem? Please describe.**
There was a video update to changing the case from the small clear/plastic case to something larger that has a larger battery and solar panel. Can the parts be shared? (hopefully with where to source them, too like Amazon links)

**Describe the solution you'd like**
Update the doc (either README.md and/or PDF with updated parts)

**Describe alternatives you've considered**
Documenting on this project's Wiki might be another option, too. Could also add docs to Slack channel. But, too many places and it is hard to maintain.

**Additional context**
More info is better! :-)

**Comment by krook** [comment]
@mkinney There's some new documentation in the [PDF](https://github.com/Code-and-Response/ClusterDuck-Protocol/blob/master/doc/HowToBuildADuck.pdf) as well as in this [directory](https://github.com/Code-and-Response/ClusterDuck-Protocol/tree/master/3D-Print-Files).
