### ISSUE TITLE
Template for printing stickers for case?

### ISSUE THREAD

**Issue by mkinney** [Code-and-Response/ClusterDuck-Protocol#17]
**Is your feature request related to a problem? Please describe.**
Is there a doc/pdf for printing the stickers on the outside of the plastic cases?

**Describe the solution you'd like**
Share location to the file(s) used to print for outside of case.

**Describe alternatives you've considered**
Would be neat to add a 2d QR code that people could scan that would take them to the website.

**Additional context**
Might help with promotion/discussions/awareness.

**Comment by TimoWielink** [comment]
I like this idea, I can definitely upload a sticker I made for one of our first Ducks. What kind of information would be useful to put on the sticker?

**Comment by mkinney** [comment]
What you used would be fine. Please share the pdf and/or source docs.

If a local situation happened (or if I wanted to deploy some ducks), I would want something on the case that would identify it as "not something suspect". (if that makes sense)

A logo, link to website and possibly a 2d QR code or something like that.

**Comment by TimoWielink** [comment]
There is a Sticker file in the asset folder.

**Comment by mkinney** [comment]
Great. Thanks!

What software was used to create that jpg? Could that file also be added? (just thinking if someone wanted to slightly alter it)

But, if not, no biggie.

**Comment by TimoWielink** [comment]
I have a psd File can share as well.

**Comment by mkinney** [comment]
That'd be great! Thanks.

**Comment by krook** [comment]
@TimoWielink is there an SVG version?

**Comment by krook** [comment]
@TimoWielink do you have a vector format or SVG?

**Comment by TimoWielink** [comment]
Yes I can provide that
