### ISSUE TITLE
CI breaks because of Vector Import in Duckutils

### ISSUE THREAD

**Issue by TimoWielink** [Code-and-Response/ClusterDuck-Protocol#245]
**Describe the bug**
Travis CI breaks with the following error:
![error](https://i.imgur.com/9yNLMY4.png)

**To reproduce**
1. Go to 'Travis Builds'
2. Click on 'Clusterduck Protocol PR'

**Expected behavior**
Compile since it does compile in arduino!!

**Additional context**
It says missing `#include <vector>` but that is added in duckutils.h

**Comment by DhruvaG2000** [comment]
I don't know if I am looking at the wrong branch, but it appears that ``#include <vector>`` is missing here: https://github.com/Call-for-Code/ClusterDuck-Protocol/blob/master/src/include/DuckUtils.h

**Comment by DhruvaG2000** [comment]
also refer: https://arduino.stackexchange.com/questions/24790/is-the-c-stl-fully-supported-on-arduino#:~:text=The%20STL%20is%20not%20a%20part%20of%20Arduino%20IDE. 

> The STL is not a part of Arduino IDE
