### ISSUE TITLE
Ghost Packets

### ISSUE THREAD

**Issue by gozu42** [Code-and-Response/ClusterDuck-Protocol#50]
**Describe the bug**

when looking at the serial log of a mamaduck, there are currently "ghost packets" that are received "right after" sending a packet.

**Additional context**

@nfeuer confirmed seeing these too, so it doesnt seem to be a local issue.

hexprinting both sent and received pkts shows the ghosts clearly contain _some_ info from the pkts sent, but are mostly garbled.

watching with a receive-only duck does not show these ghosts, so they are probably mama-internal.

since they appeared only after switching to radiolib, it is more likely to be a software issue than an actual RF or hardware one.

**Suggestions**

next step is creating a standalone sketch demonstrating the problem.

my plan is to build that based on https://github.com/gozu42/LoRaDumper (which uses the old lora lib) by adding a send component, then switch to radiolib in a "lots of defines" way (so the same "app" can be switched between the two libs easily) to see that the issue is really lora-lib specific.

this should allow to either find the issue "on the way" or have a good repro/demo sketch for filing an issue with radiolib.

Since this is mostly debug work, i do not expect any merge-conflict potential.

**Comment by gozu42** [comment]
this turns out to be caused by the way async-receive (interrupts) are handled.
the lora chip basicly has just one IRQ line that is used for all signalling, and a status register that says _which_ interrupt condition was just triggered (but is mostly ignored by radiolib).
so if we transmit a packet while in receeive mode the "transmit complete" IRQ triggers the "receive" ISR which sets the received-bool -> we think we just got a packet -> GHOSTS!

see attached (renamed) sketch for a minimal repro case.

[GhostHunter.txt](https://github.com/Code-and-Response/ClusterDuck-Protocol/files/4629242/GhostHunter.txt)

**Comment by gozu42** [comment]
after reading the semtech sx127x specs some more, the IRQs have some interesting additional potential.
for example, there is an irq that fires when a lora header was received, so we could avoid transmitting while we are actualy receiving a packet right now. == cheapish CSMA

the best way to me seems capsulating all irq handling inside radiolib.
this could be exposed as isReceiving (received header, but not complete yet) and isAvailable (complete) methods. 

i am going to suggest this over here: https://github.com/jgromes/RadioLib/issues/145
(very similar topic, recent, open)

**Comment by gozu42** [comment]
it would be good if someone else who has seen the ghost packets could confirm they are gone after https://github.com/Code-and-Response/ClusterDuck-Protocol/pull/57 before we close this one.
ping @nfeuer and @TimoWielink

**Comment by TimoWielink** [comment]
Run a test this morning and no problems for me! Thank you @gozu42 for making the changes.

**Comment by gozu42** [comment]
sounds good.
thanks for testing!
