### ISSUE TITLE
Configure SSL certificate for http://clusterduckprotocol.org/

### ISSUE THREAD

**Issue by krook** [Code-and-Response/ClusterDuck-Protocol#8]
**Describe the solution you'd like**
The http://clusterduckprotocol.org/ site needs a valid SSL certificate to support HTTPS. We can add one through Let's Encrypt or another service and configure the web host.

**Comment by krook** [comment]
Might be a starting point: https://devcenter.heroku.com/articles/ssl

**Comment by TimoWielink** [comment]
https://clusterduckprotocol.org/ Installed SSL seems to be working correctly.

**Comment by krook** [comment]
Very nice!
