### ISSUE TITLE
Update the README and PDF to specify exact ZIP file to import

### ISSUE THREAD

**Issue by krook** [Code-and-Response/ClusterDuck-Protocol#9]
**Describe the solution you'd like**
Update the README and Make a Duck Manual to mention the release ZIP file as the thing that can be imported into the Arduino environment (in addition to the source copying option). Right now it just says there's a ZIP file (which can be confused for Libraries.zip inside the repo).

This can point to either the stable release or latest from the master branch, depending on which the user wants to run:

- https://github.com/Code-and-Response/ClusterDuck-Protocol/releases
- https://github.com/Code-and-Response/ClusterDuck-Protocol/archive/master.zip

**Comment by TimoWielink** [comment]
@krook Please review the Add zip option

**Comment by krook** [comment]
Excellent, I see the [commit](https://github.com/Code-and-Response/ClusterDuck-Protocol/commit/f0e331457527cedf618b520a13841ddd830ac4cf)
